/**
 * Turn `pdftohtml -xml` output into reflowed, semantic HTML.
 *
 * Poppler's own HTML mode emits absolutely-positioned text at a fixed page
 * width: visually faithful, but unreadable on a phone and scrambled for a screen
 * reader, since the footer is often emitted before the body. Its XML mode gives
 * the same data in a form we can rebuild from -- `<text top left width height
 * font>` nodes plus a `<fontspec>` table -- so we sort by position, merge nodes
 * into lines, lines into paragraphs, and promote the bold/large ones to
 * headings.
 *
 * Parsing is regex-only, matching the deliberate choice in haverhill.mjs to
 * avoid an XML/DOM dependency. That is safe here in a way it would not be for
 * arbitrary markup: this input is machine-generated by poppler with a fixed
 * attribute order.
 *
 * Inline markup is decoded into formatting *runs* rather than carried around as
 * HTML strings. Poppler splits text at every style boundary -- a small-caps
 * heading arrives as `<b>C</b><b>ITY OF </b><b>H</b>...` and a single hyperlink
 * as three separate anchors -- so runs let us merge neighbours that share
 * formatting before rendering anything, and mean the output is escaped once, on
 * the way out.
 *
 * Everything is a pure function of the XML string so the heuristics can be
 * tested without a PDF, a binary, or the network.
 */

const PAGE_RE =
  /<page\s+number="(\d+)"[^>]*?height="([\d.]+)"\s+width="([\d.]+)"\s*>([\s\S]*?)<\/page>/g
const FONTSPEC_RE =
  /<fontspec\s+id="(\d+)"\s+size="(-?[\d.]+)"\s+family="([^"]*)"\s+color="([^"]*)"\s*\/>/g
const TEXT_RE =
  /<text\s+top="(-?[\d.]+)"\s+left="(-?[\d.]+)"\s+width="(-?[\d.]+)"\s+height="(-?[\d.]+)"\s+font="(\d+)"\s*>([\s\S]*?)<\/text>/g

/** Schemes we are willing to emit an `<a href>` for. */
const SAFE_SCHEME = /^(https?:|mailto:)/i

// --- tuning ------------------------------------------------------------------
// Ratios rather than pixel counts, so the thresholds hold across the page sizes
// and font sizes in the corpus.

/** Two nodes are on one line if they overlap vertically by this much. */
const LINE_OVERLAP = 0.5
/**
 * A horizontal gap wider than this fraction of the font size is a word break.
 * Measured across the corpus: poppler splits small-caps runs with gaps up to
 * 0.07, while genuine word spaces start at 0.17, so anything in between works.
 */
const WORD_GAP = 0.12
/** A vertical gap this many times the usual line pitch starts a paragraph. */
const PARA_GAP = 1.6
/** An indent increase this much larger than the body size starts a paragraph. */
const PARA_INDENT = 1.2
/** A line ending this far short of the text column ends its paragraph. */
const PARA_RAGGED = 0.85
/** Where the text column is taken to end, as a percentile of line right edges. */
const COLUMN_PERCENTILE = 0.9
/** Font size relative to body text that makes a line a heading. */
const HEAD_LARGE = 1.5
const HEAD_SMALL = 1.25
/** An all-bold line no longer than this many characters is a heading. */
const HEAD_MAX_CHARS = 60
/** Fraction of a line's characters that must be bold for it to count as bold. */
const BOLD_SHARE = 0.9
/** A repeated header/footer must appear on at least this fraction of pages. */
const REPEAT_SHARE = 0.5
/**
 * ...and must sit within this fraction of a page edge. Generous, because
 * letterheads in this corpus reach 18% of the way down the page.
 */
const EDGE_BAND = 0.25
/** Repeated-furniture detection only makes sense on a document this long. */
const MIN_PAGES_FOR_FURNITURE = 3
/**
 * Fraction of characters that must sit inside words for a conversion to count
 * as readable. Measured across the corpus: every genuine document scores at
 * least 0.46, while a scanned drawing whose only text layer is stray glyphs
 * scores 0.00, so anything in between separates them.
 */
const MIN_WORDLIKE = 0.2
/** Never strip more than this many lines from either end of a page... */
const MAX_FURNITURE_LINES = 8
/** ...nor more than this fraction of a page, however repetitive it looks. */
const MAX_FURNITURE_SHARE = 0.5

const escapeHtml = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")

/** Decode the handful of entities poppler emits. */
const decodeEntities = (s) =>
  s
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(+d))
    .replace(/&nbsp;/g, " ")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")

/**
 * Split a node's inline markup into `{text, bold, italic, href}` runs.
 *
 * Only `<b>`, `<i>` and a scheme-checked `<a href>` carry any meaning; every
 * other tag is dropped and its text kept. An `href` that is not http(s) or
 * mailto becomes plain text rather than a link, so the rendered output cannot
 * contain a `javascript:` URL no matter what the PDF held.
 */
export function parseRuns(html) {
  const runs = []
  const stack = []
  let bold = 0
  let italic = 0
  let href = null
  let last = 0

  const push = (raw) => {
    // Non-breaking spaces are layout, not content: they would defeat the
    // whitespace collapsing every downstream heuristic depends on.
    const text = decodeEntities(raw).replace(/\u00a0/g, " ")
    if (text) runs.push({ text, bold: bold > 0, italic: italic > 0, href })
  }

  for (const match of html.matchAll(/<[^>]*>/g)) {
    push(html.slice(last, match.index))
    last = match.index + match[0].length

    const tag = match[0]
    const name = tag.match(/^<\/?\s*([a-z]+)/i)?.[1]?.toLowerCase()

    if (tag.startsWith("</")) {
      const at = stack.lastIndexOf(name)
      if (at === -1) continue // stray closer
      stack.splice(at, 1)
      if (name === "b") bold = Math.max(0, bold - 1)
      else if (name === "i") italic = Math.max(0, italic - 1)
      else if (name === "a") href = null
    } else if (name === "b") {
      stack.push("b")
      bold++
    } else if (name === "i") {
      stack.push("i")
      italic++
    } else if (name === "a") {
      const raw = decodeEntities(tag.match(/href="([^"]*)"/)?.[1] ?? "").trim()
      stack.push("a")
      href = SAFE_SCHEME.test(raw) ? raw : null
    }
  }
  push(html.slice(last))
  return runs
}

/**
 * Collapse runs that share formatting, and unwrap links whose text is only
 * whitespace -- poppler emits a separate anchor for the space either side of a
 * URL, which would otherwise render as three consecutive copies of the link.
 */
function mergeRuns(runs) {
  const out = []
  for (const run of runs) {
    const next = run.href && !run.text.trim() ? { ...run, href: null } : run
    const prev = out.at(-1)
    if (prev && prev.bold === next.bold && prev.italic === next.italic && prev.href === next.href) {
      prev.text += next.text
    } else {
      out.push({ ...next })
    }
  }
  return out
}

function renderRuns(runs) {
  return runs
    .map((run) => {
      let html = escapeHtml(run.text)
      if (run.italic) html = `<i>${html}</i>`
      if (run.bold) html = `<b>${html}</b>`
      if (run.href) {
        html = `<a href="${escapeHtml(run.href)}" target="_blank" rel="external noopener noreferrer">${html}</a>`
      }
      return html
    })
    .join("")
}

/** Weighted median: `values[i]` counts `weights[i]` times. */
function weightedMedian(values, weights) {
  const pairs = values.map((v, i) => [v, weights[i]]).sort((a, b) => a[0] - b[0])
  const total = pairs.reduce((n, [, w]) => n + w, 0)
  if (!total) return 0
  let seen = 0
  for (const [value, weight] of pairs) {
    seen += weight
    if (seen >= total / 2) return value
  }
  return pairs.at(-1)[0]
}

const median = (nums) => percentile(nums, 0.5)

/**
 * `p` of the way through the sorted values. Used with a high `p` to find where
 * the text column ends: a median would be pulled left by an address block or a
 * list of short lines, and the max by a single line bleeding into the margin.
 */
function percentile(nums, p) {
  if (!nums.length) return 0
  const sorted = [...nums].sort((a, b) => a - b)
  return sorted[Math.min(sorted.length - 1, Math.round(p * (sorted.length - 1)))]
}

const textOf = (runs) => runs.map((r) => r.text).join("")
const nonSpace = (s) => s.replace(/\s/g, "").length

function parseFonts(xml) {
  const fonts = new Map()
  for (const [, id, size, family, color] of xml.matchAll(FONTSPEC_RE)) {
    fonts.set(id, { size: Number(size), family, color })
  }
  return fonts
}

function parseNodes(body, fonts) {
  const nodes = []
  for (const [, top, left, width, height, font, html] of body.matchAll(TEXT_RE)) {
    const runs = mergeRuns(parseRuns(html))
    // Poppler emits a lot of whitespace-only spacer nodes; they carry no
    // content but would otherwise widen every line's bounding box.
    if (!textOf(runs).trim()) continue
    nodes.push({
      top: Number(top),
      left: Number(left),
      right: Number(left) + Number(width),
      bottom: Number(top) + Number(height),
      height: Number(height),
      size: fonts.get(font)?.size ?? Number(height),
      runs,
    })
  }
  return nodes
}

/**
 * Group nodes into visual lines.
 *
 * Vertical overlap rather than an equal `top`: poppler splits a small-caps
 * heading into runs set at different sizes, so `top=51 height=50` and `top=59
 * height=39` are the same visual line despite disagreeing on where they start.
 */
function buildLines(nodes) {
  const grouped = []
  for (const node of [...nodes].sort((a, b) => a.top - b.top || a.left - b.left)) {
    const line = grouped.at(-1)
    const overlap = line ? Math.min(node.bottom, line.bottom) - Math.max(node.top, line.top) : 0
    if (line && overlap >= LINE_OVERLAP * Math.min(node.height, line.bottom - line.top)) {
      line.nodes.push(node)
      line.top = Math.min(line.top, node.top)
      line.bottom = Math.max(line.bottom, node.bottom)
    } else {
      grouped.push({ top: node.top, bottom: node.bottom, nodes: [node] })
    }
  }

  return grouped.map((line) => {
    const ordered = [...line.nodes].sort((a, b) => a.left - b.left)
    let runs = []
    let prev = null
    for (const node of ordered) {
      // Poppler rarely emits the space between two runs, so infer one from the
      // horizontal gap. Scaled by font size, since a gap that is a word break
      // at 9px is mid-word at 39px.
      if (prev && node.left - prev.right > WORD_GAP * node.size && !/\s$/.test(textOf(runs))) {
        runs.push({ text: " ", bold: false, italic: false, href: null })
      }
      runs = runs.concat(node.runs)
      prev = node
    }
    runs = mergeRuns(runs)

    const text = textOf(runs).replace(/\s+/g, " ").trim()
    const boldChars = runs.filter((r) => r.bold).reduce((n, r) => n + nonSpace(r.text), 0)
    return {
      top: line.top,
      bottom: line.bottom,
      left: ordered[0].left,
      right: ordered.at(-1).right,
      size: weightedMedian(
        ordered.map((n) => n.size),
        ordered.map((n) => nonSpace(textOf(n.runs))),
      ),
      // Compared on non-space characters: a mostly-bold line whose inter-word
      // spaces happen to fall outside the <b> runs is still a bold line.
      bold: boldChars >= BOLD_SHARE * nonSpace(text),
      text,
      html: renderRuns(runs).trim(),
    }
  })
}

/**
 * Strip running headers and footers.
 *
 * Two signals, and furniture needs both. Repetition alone is not safe: `Second:
 * seconded.` recurs on most pages of a set of minutes and is real content, and
 * content sitting directly above a repeated footer repeats along with it. A
 * margin band alone is not safe either, since body text starts inside the band
 * on plenty of documents.
 *
 * So: take the lines at each page's top and bottom margins, then find the
 * longest leading and trailing runs of those that at least half the pages agree
 * on, and drop them. Anything mid-page survives however often it recurs.
 */
function stripFurniture(pages) {
  if (pages.length < MIN_PAGES_FOR_FURNITURE) return pages.map((p) => p.lines)

  const keys = pages.map((p) => p.lines.map((l) => furnitureKey(l.text)))
  const margins = pages.map((page, i) => {
    const band = EDGE_BAND * page.height
    let head = 0
    while (head < page.lines.length && page.lines[head].top <= band) head++
    let tail = 0
    while (tail < page.lines.length && page.lines.at(-1 - tail).bottom >= page.height - band) tail++
    return { head: keys[i].slice(0, head), tail: keys[i].slice(keys[i].length - tail) }
  })

  const head = commonRunLength(
    margins.map((m) => m.head),
    "start",
    pages.length,
  )
  const tail = commonRunLength(
    margins.map((m) => m.tail),
    "end",
    pages.length,
  )

  return pages.map((page, i) => {
    // However repetitive a document looks, never strip a page to nothing.
    const limit = Math.floor(page.lines.length * MAX_FURNITURE_SHARE)
    const from = Math.min(matches(margins[i].head, margins, "start", head, pages.length), limit)
    const drop = Math.min(matches(margins[i].tail, margins, "end", tail, pages.length), limit)
    return page.lines.slice(from, drop ? page.lines.length - drop : undefined)
  })
}

/** `n` if this page carries the run the majority agreed on, otherwise 0. */
const matches = (page, margins, edge, n, total) =>
  n > 0 && page.length >= n && runOf(page, n, edge) === modalRun(margins, edge, n, total).run
    ? n
    : 0

/** The `n` first (or last) keys of a run, as one comparable string. */
const runOf = (keys, n, edge) =>
  (edge === "start" ? keys.slice(0, n) : keys.slice(keys.length - n)).join("\u0000")

/** The most common `n`-line run at `edge`, and how many pages carry it. */
function modalRun(margins, edge, n) {
  const counts = new Map()
  for (const margin of margins) {
    const keys = edge === "start" ? margin.head : margin.tail
    if (keys.length < n) continue
    const run = runOf(keys, n, edge)
    counts.set(run, (counts.get(run) ?? 0) + 1)
  }
  let best = { run: null, count: 0 }
  for (const [run, count] of counts) if (count > best.count) best = { run, count }
  return best
}

/** The longest run at `edge` that enough of the pages agree on. */
function commonRunLength(runs, edge, total) {
  const margins = runs.map((keys) => (edge === "start" ? { head: keys } : { tail: keys }))
  let found = 0
  for (let n = 1; n <= MAX_FURNITURE_LINES; n++) {
    if (modalRun(margins, edge, n).count >= REPEAT_SHARE * total) found = n
    else break
  }
  return found
}

/**
 * Compare lines with page numbers neutralised, so `Page 1 of 18` and `Page 2 of
 * 18` count as the same footer. Only short lines: blanking digits in a whole
 * sentence makes `Item 1 was taken up` and `Item 2 was taken up` identical, and
 * body text would then be mistaken for furniture.
 */
const FURNITURE_MAX_CHARS = 40
const furnitureKey = (text) =>
  text.length <= FURNITURE_MAX_CHARS ? text.replace(/\d+/g, "#") : text

/**
 * A numbered agenda item: `3.`, `1.1.`, `2.1`. Deliberately does not match a
 * bare year, so `2026 was a busy year` is not mistaken for a section number.
 */
const SECTION_NUMBER = /^(\d+\.\s|\d+(\.\d+)+\.?\s)/

/** Is this line set mostly in capitals, the way section heads here are? */
function mostlyUpper(text) {
  const letters = text.replace(/[^A-Za-z]/g, "")
  if (letters.length < 3) return false
  return letters.replace(/[^A-Z]/g, "").length / letters.length >= 0.6
}

/**
 * Decide whether a line is a heading, and how strong a one.
 *
 * Being bold and short is not enough on its own: minutes bold the applicant's
 * name, trading name and street address under each agenda item, and promoting
 * all of those buries the real structure. A bold line also has to *look* like a
 * section head -- numbered, or set in capitals.
 */
function headingRank(line, bodySize) {
  if (line.size >= HEAD_LARGE * bodySize) return 1
  if (line.size >= HEAD_SMALL * bodySize) return 2
  if (
    line.bold &&
    line.text.length <= HEAD_MAX_CHARS &&
    (SECTION_NUMBER.test(line.text) || mostlyUpper(line.text))
  ) {
    return 3
  }
  return 0
}

/** Numbered agenda items always start their own block. */
const startsListItem = (text) => SECTION_NUMBER.test(text)

/**
 * Group a page's body lines into paragraphs.
 *
 * Municipal agendas are set with uniform leading, so a vertical gap alone does
 * not find the breaks. The load-bearing signal is an indent *increase*: a
 * first-line indent starts a paragraph, and the wrapped lines beneath it sit
 * further left. A ragged short line ends one.
 *
 * `column` is where the page's text column ends, and must be measured over the
 * whole page rather than the lines passed in: an address block is five short
 * lines in a row, and judged only against each other none of them looks ragged.
 */
function groupParagraphs(lines, bodySize, pitch, column) {
  const paragraphs = []
  let current = null
  let prev = null

  for (const line of lines) {
    const breaks =
      !prev ||
      line.top - prev.bottom > PARA_GAP * pitch ||
      line.left - prev.left > PARA_INDENT * bodySize ||
      prev.right < PARA_RAGGED * column ||
      startsListItem(line.text)

    if (breaks) {
      current = [line]
      paragraphs.push(current)
    } else {
      current.push(line)
    }
    prev = line
  }
  return paragraphs
}

/**
 * Convert one `pdftohtml -xml` document into a body-HTML fragment.
 *
 * Returns `''` for a PDF with no text layer -- roughly half this corpus is
 * scanned images, and poppler reports those as pages containing no `<text>`
 * nodes at all. Callers use an empty result to tell a scan from a failure.
 */
export function convertXmlToHtml(xml) {
  const fonts = parseFonts(xml)
  const pages = []
  for (const [, number, height, width, body] of xml.matchAll(PAGE_RE)) {
    pages.push({
      number: Number(number),
      height: Number(height),
      width: Number(width),
      lines: buildLines(parseNodes(body, fonts)),
    })
  }

  const allLines = pages.flatMap((p) => p.lines)
  if (!allLines.length) return ""

  // Body size drives every relative threshold, so measure it by how much text
  // is set at each size rather than by how many lines use it: a two-line 36px
  // title should not out-vote forty lines of 18px body copy.
  const bodySize = weightedMedian(
    allLines.map((l) => l.size),
    allLines.map((l) => l.text.length),
  )
  const pitch =
    median(
      pages
        .flatMap((p) => p.lines.slice(1).map((line, i) => line.top - p.lines[i].top))
        .filter((gap) => gap > 0),
    ) || bodySize

  const bodyLines = stripFurniture(pages)

  // Collect blocks first so heading levels can be normalised across the whole
  // document before any HTML is emitted.
  const blocks = []
  for (const [i, page] of pages.entries()) {
    const kept = bodyLines[i]
    if (!kept.length) continue
    blocks.push({ type: "page-start", number: page.number })

    const column = percentile(
      kept.map((l) => l.right),
      COLUMN_PERCENTILE,
    )
    let run = []
    const flush = () => {
      for (const paragraph of groupParagraphs(run, bodySize, pitch, column)) {
        blocks.push({ type: "p", html: paragraph.map((l) => l.html).join(" ") })
      }
      run = []
    }

    for (const line of kept) {
      const rank = headingRank(line, bodySize)
      if (rank) {
        flush()
        blocks.push({ type: "heading", rank, html: line.html })
      } else {
        run.push(line)
      }
    }
    flush()
    blocks.push({ type: "page-end" })
  }

  // Map the ranks actually used onto consecutive levels starting at h2, so a
  // document whose only headings are bold agenda items does not jump from the
  // page's h1 straight to h4.
  const used = [...new Set(blocks.filter((b) => b.type === "heading").map((b) => b.rank))].sort(
    (a, b) => a - b,
  )
  const level = new Map(used.map((rank, i) => [rank, Math.min(2 + i, 6)]))

  const out = []
  for (const block of blocks) {
    if (block.type === "page-start") out.push(`<section aria-label="Page ${block.number}">`)
    else if (block.type === "page-end") out.push("</section>")
    else if (block.type === "heading") {
      const h = level.get(block.rank)
      out.push(`<h${h}>${block.html}</h${h}>`)
    } else if (block.html.trim()) out.push(`<p>${block.html}</p>`)
  }
  return out.join("\n") + "\n"
}

/**
 * Did the conversion produce actual prose, or just noise?
 *
 * Most scans have no text layer at all and convert to nothing, which is easy to
 * detect. But a scanned engineering drawing can carry a handful of vector glyphs
 * -- an 82 MB, 481-page Council packet converts to 416 characters of
 * `e ::I JI 11I I I 0 I` -- and that is a scan too, however non-empty. Measuring
 * how much of the text sits inside real words separates the two cleanly, where
 * counting characters per page would not: several Council agendas are a genuine
 * text-layer agenda followed by two hundred pages of scanned attachments, and
 * their prose is worth keeping.
 */
export function hasReadableText(html) {
  const text = decodeEntities(html.replace(/<[^>]+>/g, " "))
  const dense = text.replace(/\s/g, "").length
  if (!dense) return false
  const inWords = (text.match(/[A-Za-z]{3,}/g) ?? []).join("").length
  return inWords / dense >= MIN_WORDLIKE
}
